/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpexValues } from './OpexValues';
import {
    OpexValuesFromJSON,
    OpexValuesFromJSONTyped,
    OpexValuesToJSON,
} from './OpexValues';

/**
 * 
 * @export
 * @interface Opex
 */
export interface Opex {
    /**
     * 
     * @type {OpexValues}
     * @memberof Opex
     */
    perWeek?: OpexValues;
    /**
     * 
     * @type {OpexValues}
     * @memberof Opex
     */
    perYear?: OpexValues;
    /**
     * 
     * @type {OpexValues}
     * @memberof Opex
     */
    overLifetime?: OpexValues;
    /**
     * The assumed operational lifetime of the machines in years
     * @type {number}
     * @memberof Opex
     */
    operationalLifetime?: number;
}

/**
 * Check if a given object implements the Opex interface.
 */
export function instanceOfOpex(value: object): value is Opex {
    return true;
}

export function OpexFromJSON(json: any): Opex {
    return OpexFromJSONTyped(json, false);
}

export function OpexFromJSONTyped(json: any, ignoreDiscriminator: boolean): Opex {
    if (json == null) {
        return json;
    }
    return {
        
        'perWeek': json['perWeek'] == null ? undefined : OpexValuesFromJSON(json['perWeek']),
        'perYear': json['perYear'] == null ? undefined : OpexValuesFromJSON(json['perYear']),
        'overLifetime': json['overLifetime'] == null ? undefined : OpexValuesFromJSON(json['overLifetime']),
        'operationalLifetime': json['operationalLifetime'] == null ? undefined : json['operationalLifetime'],
    };
}

export function OpexToJSON(value?: Opex | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'perWeek': OpexValuesToJSON(value['perWeek']),
        'perYear': OpexValuesToJSON(value['perYear']),
        'overLifetime': OpexValuesToJSON(value['overLifetime']),
        'operationalLifetime': value['operationalLifetime'],
    };
}

