/* tslint:disable */
/* eslint-disable */
/**
 * Household savings
 * This is the API for a household savings model. You can provide details about a household\'s energy use, and receive information about the household\'s potential emissions & cost savings from electrifying their fossil fuel machines, as well as the upfront costs of switching.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OpexValues
 */
export interface OpexValues {
    /**
     * The household's opex costs per week before electrification in NZD to 2 dp.
     * @type {number}
     * @memberof OpexValues
     */
    before?: number;
    /**
     * The household's opex costs per week after electrification in NZD to 2 dp.
     * @type {number}
     * @memberof OpexValues
     */
    after?: number;
    /**
     * The savings value; the difference in opex costs before & after electrification, in NZD to 2 dp.
     * @type {number}
     * @memberof OpexValues
     */
    difference?: number;
}

/**
 * Check if a given object implements the OpexValues interface.
 */
export function instanceOfOpexValues(value: object): value is OpexValues {
    return true;
}

export function OpexValuesFromJSON(json: any): OpexValues {
    return OpexValuesFromJSONTyped(json, false);
}

export function OpexValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpexValues {
    if (json == null) {
        return json;
    }
    return {
        
        'before': json['before'] == null ? undefined : json['before'],
        'after': json['after'] == null ? undefined : json['after'],
        'difference': json['difference'] == null ? undefined : json['difference'],
    };
}

export function OpexValuesToJSON(value?: OpexValues | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'before': value['before'],
        'after': value['after'],
        'difference': value['difference'],
    };
}

